---
- name: Loops with Hashes
  hosts: all
  become: true
  tasks:
    - name: Loops having hashes
      user:
        name: "{{ item.name }}"
        group: "{{ item.groups }}"
        state: present
      loop:
        - { name: 'test5', groups: "root" }
    - name: Loop without hashes
      user:
        name: "{{ item }}"
        state: present
      loop:
        - test7  